export const STUDENT_REGIONS = [
  "Abia State University Teaching Hospital - ABSUTH Chapter",
  "Ahmadu Bello University Teaching Hospital - ABUTH Chapter",
  "Afe Babalola University Teaching Hospital - ABUADTH Chapter",
  "Abubakar Tafawa Balewa University Teaching Hospital - ATBUTH Chapter",
  "Aminu Kano University Teaching Hospital - AKTH Chapter",
  "Alex Ekwueme University Teaching Hospital - AEFUTH Chapter",
  "Ambrose Alli University/ Irrua Specialist Teaching Hospital - AAU/ISTH Chapter",
  "Bowen University Teaching Hospital - BUTH Chapter",
  "Barau-Dikko University Teaching Hospital - BDTH-KASU Chapter",
  "Bingham University Teaching Hospital - BHUTH Chapter",
  "Benue State University Teaching Hospital - BSUTH Chapter",
  "Chukwuemeka Odumegwu Ojukwu University Teaching Hospital - COOUTH Chapter",
  "Delta State University Teaching Hospital - DELSUTH Chapter",
  "Ebonyi State University Teaching Hospital - EBSUTH Chapter",
  "Ekiti State University Teaching Hospital - EKSUTH Chapter",
  "Enugu State University Teaching Hospital - ESUTH Chapter",
  "Gombe State University Teaching Hospital - GSUTH Chapter",
  "Gregory University Teaching Hospital - GUTH Chapter",
  "Igbinedion University Teaching Hospital - IUTH Chapter",
  "Imo State University Teaching Hospital - IMSUTH Chapter",
  "Jos University Teaching Hospital - JUTH Chapter",
  "University of Medical Sciences Teaching Hospital (UNIMEDTH) Chapter",
  "Lagos State University Teaching Hospital - LASUTH Chapter",
  "Lagos University Teaching Hospital - LUTH Chapter",
  "Lautech Teaching Hospital - LTH Chapter",
  "Niger Delta University Teaching Hospital - NDUTH Chapter",
  "Nnamdi Azikiwe University Teaching Hospital - NAUTH Chapter",
  "Obafemi Awolowo University Teaching Hospital - OAUTH Chapter",
  "Olabisi Onabanjo University Teaching Hospital - OOUTH Chapter",
  "Osun State University Teaching Hospital - UNIOSUNTH Chapter",
  "University of Abuja Teaching Hospital - UATH Chapter",
  "Usman Dan Fodio University Teaching Hospital - UDUTH Chapter",
  "University College Hospital - UCH Chapter",
  "University of Nigeria Teaching Hospital - UNTH Chapter",
  "University of Benin Teaching Hospital - UBTH Chapter",
  "University of Calabar Teaching Hospital - UCTH Chapter",
  "University of Ilorin Teaching Hospital - UITH Chapter",
  "University of Maiduguri Teaching Hospital - UMTH Chapter",
  "University of Port Harcourt Teaching Hospital - UPTH Chapter",
  "University of Uyo Teaching Hospital – UUTH Chapter",
];

export const DOCTOR_REGIONS = [
  "Abia - Umahia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra (NAUTH)",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "CMDA Uyo",
  "Cross River",
  "Delta - DELSUTH, Oghara",
  "Delta FMC, Asaba",
  "Ebonyi",
  "Edo-Benin",
  "Edo-SHMB",
  "Edo-Irrua",
  "Ekiti - Ido",
  "Ekiti-Ado",
  "Enugu",
  "FCT Gwagwalada",
  "FCT Municipal",
  "Gombe",
  "Imo",
  "Kaduna - Kaduna",
  "Kaduna - Zaria",
  "Kano",
  "Kogi",
  "Kwara",
  "Lagos-Lasuth",
  "Lagos-Luth",
  "Nasarawa - Keffi",
  "Nasarawa - Lafiya",
  "Niger-Bida",
  "Ogun - Abeokuta",
  "Ogun - Shagamu",
  "Ondo - Owo",
  "ONDO - UNIMEDTH",
  "Osun-Ife",
  "Osun-Osogbo",
  "Oyo",
  "LAUTECH",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Kebbi",
];

export const GLOBAL_NETWORK_REGIONS = [
  "The Americas Region",
  "UK/Europe region",
  "Australasia Region",
  "Middle East Region",
  "Africa Region",
];
